jobs:
  - job: hisi_upload
    timeoutInMinutes: 360
    pool:
      vmImage: Ubuntu 18.04
    steps:
      - checkout: self
        clean: true
      - script: ./run.sh
        env:
          BOTTOKEN: $(bottoken)

      #- task: PublishBuildArtifacts@1
      #  displayName: Publish packages
      #  inputs:
      #    pathtoPublish: $(Build.SourcesDirectory)/artifacts
#artifactName: mingw-$(MINGW_ARCH)
