jobs:
  - job: hisi_upload
    timeoutInMinutes: 360
    pool:
      vmImage: Ubuntu 16.04
    steps:
      - checkout: self
        clean: true
      - script: ls
      #- task: PublishBuildArtifacts@1
      #  displayName: Publish packages
      #  inputs:
      #    pathtoPublish: $(Build.SourcesDirectory)/artifacts
#artifactName: mingw-$(MINGW_ARCH)